### ISSUE TITLE
error when tryingcto publish

### ISSUE THREAD

**Issue by javadroid** [natedotv2/fantoken-tutoral#1]
when ever i run _aptos move publish_

this is what returns

C:\Users\user\Documents\Projects\token\aptos>aptos move publish
Compiling, may take a little while to download git dependencies...
INCLUDING DEPENDENCY AptosFramework
INCLUDING DEPENDENCY AptosStdlib
INCLUDING DEPENDENCY MoveStdlib
BUILDING nuklean
package size 2042 bytes
{
  "Error": "Simulation failed with status: Transaction Executed and Committed with Error BACKWARD_INCOMPATIBLE_MODULE_UPDATE"
}

**this is my code:**

address admin{

    module nuklean{
        use aptos_framework::coin;
        use std::signer;
        use std::string;

        struct NUKs{}

        struct CoinCapabilities<phantom NUKs> has key {
            mint_capability: coin::MintCapability<NUKs>,
            burn_capability: coin::BurnCapability<NUKs>,
            freeze_capability: coin::FreezeCapability<NUKs>
        }

        const E_NO_ADMIN:u64 =0;
        const E_NO_CAPABILITY:u64 =1;
        const E_HAS_CAPABILITY:u64 =2;

        public entry fun init_nuk(account: &signer){
            let(burn_capability,freeze_capability,mint_capability)=coin::initialize<NUKs>(
                account,
                string::utf8(b"Nuklean"),
                string::utf8(b"NUKs"),
                18,
                true
            );

            assert!(signer::address_of(account)==@admin,E_NO_ADMIN);
            assert!(!exists<CoinCapabilities<NUKs>>(@admin),E_HAS_CAPABILITY);

            move_to<CoinCapabilities<NUKs>>(account,CoinCapabilities<NUKs>{mint_capability,burn_capability,freeze_capability});
            
        }

         public fun mint<NUKs>(account: &signer,user:address ,amount:u64) acquires CoinCapabilities{
            let account_address = signer::address_of(account);
            assert!(account_address==@admin,E_NO_ADMIN);
            assert!(!exists<CoinCapabilities<NUKs>>(account_address),E_NO_CAPABILITY);
            let mint_capability= &borrow_global<CoinCapabilities<NUKs>>(account_address).mint_capability;
            let coins = coin::mint<NUKs>(amount,mint_capability);
            coin::deposit<NUKs>(user,coins)
        }
        
        public fun burn<NUKs>(coin: coin::Coin<NUKs>) acquires CoinCapabilities {
            let burn_capability= &borrow_global<CoinCapabilities<NUKs>>(@admin).burn_capability;
            coin::burn<NUKs>(coin,burn_capability);
        }
    }
}

**Comment by 0xNeit** [comment]
you must have published the package before using thesame account. You get this
```{
"Error": "Simulation failed with status: Transaction Executed and Committed with Error BACKWARD_INCOMPATIBLE_MODULE_UPDATE"
}```
error when you try to change a struct definition or add a new Struct type to a function. Just make sure that whatever update you make after publishing the first time does not change any struct. If you are not sure what you changed, just copy the code and initialize a new move package and deploy again with a different account

**Comment by javadroid** [comment]
yes i get, i had to change the name 
thanks
